source "https://rubygems.org"

#gem "github-pages", group: :jekyll_plugins
gem "jekyll", ">= 4.2.0"
# TODO: use official gem
gem "dendron-jekyll", path: "/Users/kevinlin/projects/dendronv2/dendron-just-the-docs/"
